/**
 * Invisible sub-tags for quote pattern diversity.
 * Used in Grok API prompts to vary quote structure.
 */
export const SUB_TAGS: string[] = [
  'Simple fact listing + conclusion',
  'Present progressive declaration',
  'Strong positive repetition',
  'Short single sentence declaration',
  'Be / Do / Love imperative',
  'Never do… Be the…',
  'You must… if you wish to…',
  'Normalize…',
  'If you… then…',
  'The real strength is in… without…',
  'What you give out will always return',
  'Self question + positive answer',
  'Challenge question + solution answer',
  'Emotion question + comfort answer',
  'Future-oriented question + confident answer',
  'Nature metaphor',
  'Journey/path metaphor',
  'Object/tool metaphor',
  'Animal/life metaphor',
  'Personal story + lesson',
  'History/famous person story',
  'Imagination story + twist',
  'Daily story + application',
  'Emphasis through comparison',
  'Declaration with twist',
  'Emotion shift instruction',
  'List format + conclusion',
  'Advice through metaphor',
  'Past reflection + future orientation',
  'Balance emphasis declaration',
  'Confidence through repetition',
  'Choice freedom emphasis',
  'Change urging command',
  'Gratitude-centered list',
  'Challenge overcoming metaphor',
  'Relationship-centered advice',
  'Self-love declaration',
  'Time management instruction',
  'Failure redefinition',
  'Success formula list',
  'Mindfulness question',
  'Inspiring historical metaphor',
  'Secret discovery in daily life',
  'Energy flow metaphor',
  'Balance and harmony emphasis',
  'Courage-giving repetition',
  'Peaceful state declaration',
  'Growth process metaphor',
  'Gratitude journal instruction',
  'Emotion acknowledgment + overcoming',
  'Creativity-promoting question',
  'Relationship healing advice',
  'Healthy habit list',
  'Financial freedom declaration',
  'Environmental impact emphasis',
  'Meditation guide instruction',
  'Dream realization stages',
  'Empathy-based comfort',
  'Nature healing metaphor',
  'Leadership principles list',
  'Rest importance declaration',
  'Change acceptance question',
  'Family love emphasis',
  'Friend choice advice',
  'Learning passion repetition',
  'Failure learning metaphor',
  'Hope maintenance instruction',
  'Positive mindset declaration',
  'Challenge acceptance metaphor',
  'Emotion balance list',
  'Goal setting instruction',
  'Self-reflection question',
  'Forgiveness process metaphor',
  'Happiness definition declaration',
  'Energy protection advice',
  'Creative thinking emphasis',
  'Relationship balance list',
  'Dream pursuit question',
  'Forgiveness healing metaphor',
];

export function getRandomSubTag(): string {
  return SUB_TAGS[Math.floor(Math.random() * SUB_TAGS.length)];
}
